- .github/auto_assign.yml
- gcp-gke/main.tf
- test/README.md
> fix(terraform/GCP): service account credentials

- gcp-gke/main.tf
> fix(terraform): relax version requirement to 0.12.28-0.13.x

- gcp-gke/main.tf
> fix(local-exec): interpreter issue using <<<

- gcp-gke/main.tf
- gcp-gke/variables.tf
- remote-backend.tf
- test/gke_test.go
- variables.tf
JIRA: https://honestbank.atlassian.net/browse/DEVOPS-38
Description: This PR adds the installation of cert-manager (v0.16.1) into the cluster.
> feat(cert-manager): add cert-manager installation [DEVOPS-38]

- gcp-gke/modules/bootstrap/main.tf
- test/gke_test.go
- test/terratest_options.go
> refactor(terraform): migrate shell-exec to kubernetes resources

- gcp-gke/main.tf
- remote-backend.tf
> chore(terraform): require Terraform 0.13.1 upwards

- .github/workflows/gitguardian.yml
> ci(gitguardian): add GitGuardian Github Action

- .github/workflows/release.yaml
> ci(release): add semver release workflow

- .github/CODEOWNERS
https://honestbank.atlassian.net/browse/DEVOPS-153
> chore(codeowners): add CODEOWNERS file [DEVOPS-153]

- .github/workflows/release.yaml
> ci(release): trigger on ‘main’ branch

- .github/workflows/release.yaml
> ci(release): set release_branches = main

- gcp-gke/modules/bootstrap/elastic/elastic-basic-cluster.yaml
- gcp-gke/modules/bootstrap/elastic/elastic-filebeat.yaml
> fix(elasticsearch): remove invalid/unknown manifest values

- .github/workflows/terratest.yml
- gcp-gke/modules/bootstrap/elastic/elastic-basic-cluster.yaml
- gcp-gke/modules/bootstrap/elastic/elastic-filebeat.yaml
- gcp-gke/modules/bootstrap/elastic/elastic-kibana.yaml
- gcp-gke/modules/bootstrap/main.tf
- test/prepare-test-environment.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/37)
> fix(elasticsearch): update ECK and elasticsearch manifests

- .github/workflows/shiftleft.yml
This pull request adds a GitHub Action workflow file that executes ShiftLeft NextGen SAST (NG SAST) on this PR. Once merged, it will also execute NG SAST on all future PRs opened in this repo.
- Created a new branch and opened this pull request
- Generated a unique secret `SHIFTLEFT_ACCESS_TOKEN` to allow GitHub Actions in this repository to communicate with the ShiftLeft API
- Created a [GitHub Action](https://github.com/Honestbank/terraform-gcp-gke/blob/shiftleft-action-config-1603963609/.github/workflows/shiftleft.yml) that will send this pull request to ShiftLeft for analysis
- Added a status check that displays the result of the GitHub Action
Questions? Comments? Want to learn more? [Get in touch with us](https://www.shiftleft.io/contact/) or check out [our …
> ci(security): add ShiftLeft scanning workflow

- .github/workflows/terratest.yml
- gcp-gke/main.tf
- gcp-gke/modules/bootstrap/main.tf
- test/gke_test.go
- test/prepare-test-environment.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/39)
> test(terratest): fix failing test [DEVOPS-141]

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/40)
> fix(readme): update Terratest badge

- gcp-gke/main.tf
- gcp-gke/modules/bootstrap/main.tf
- test/README.md
- test/gke_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/45)
> chore(eck)!: bump version, remove resources

- .github/pull_request_template.md
JIRA Issue/s:
* DEVOPS-124
Description: 
* Adds a PR template
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/43)
> docs(pull_request_template): add template [DEVOPS-124]

- .deepsource.toml
- gcp-gke/main.tf
JIRA Issue/s:
* DEVOPS-201
Description: 
* Enables the HTTP load balancing feature of GKE to enable support for Ingress objects
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/48)
> feat(gke): enable http_load_balancing [DEVOPS-201]

- README.md
- gcp-gke/README.md
- gcp-gke/main.tf
- gcp-gke/network.tf
- gcp-gke/outputs.tf
- outputs.tf
- wrapper.auto.tfvars
* Fix firewall rule for Istio/Gatekeeper by applying a custom tag to the node pool and using that tag in the firewall rule
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/64)
> fix: Firewall rule to allow Gatekeeper webhooks to function

- gcp-gke/main.tf
- gcp-gke/network.tf
* Specify Service Account for GKE cluster/initial node pool
* Specify VPC Google provider for Firewall rule creation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/65)
> fix: GKE Service Account, Firewall provider

- gcp-gke/README.md
- gcp-gke/main.tf
- main.tf
- wrapper.auto.tfvars
* The `release_channel` was previously hardcoded to `RAPID`, this change removes the hardcode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/69)
> fix(inputs): Use release_channel variable

- .github/workflows/terratest.yml
- gcp-gke/main.tf
* Update gcloud action
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/73)
> ci(terratest): Pin gcloud to v0 [DEVOP-1015, DEVOP-1014]

- .pre-commit-config.yaml
- README.md
- catalog-info.yaml
- modules/gcp-gke/README.md
* Add catalog info
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/78)
> docs(catalog-info): add service catalog

- .github/workflows/checkov.yaml
- .github/workflows/semantic-pr.yaml
- .github/workflows/shiftleft-terraform.yaml
- .github/workflows/terraform.yaml
- .github/workflows/terratest.yaml
- main.tf
- modules/gcp-gke/README.md
- modules/gcp-gke/inputs.tf
- modules/gcp-gke/main.tf
- modules/gcp-gke/modules/gcp-gke-node-pool/inputs.tf
- modules/gcp-gke/modules/gcp-gke-node-pool/node-pool.tf
- modules/gcp-gke/node-pools.tf
- test/gke_test.go
- test/wrapper.auto.tfvars
* support for taint added
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/87)
> feat: add taint for nodes for high resource usage workloads

- main.tf
- modules/gcp-gke/README.md
- modules/gcp-gke/inputs.tf
- modules/gcp-gke/modules/gcp-gke-node-pool/inputs.tf
- modules/gcp-gke/modules/gcp-gke-node-pool/node-pool.tf
- modules/gcp-gke/node-pools.tf
- test/wrapper.auto.tfvars
* This change exposes zones for node-pools
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/90)
> feat: expose zones for node-pools

- modules/gcp-gke/inputs.tf
* extra zone variable removed
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/91)
> refactor: remove redundant zone variable

- modules/gcp-gke/main.tf
- modules/gcp-gke/modules/gcp-gke-node-pool/node-pool.tf
* node pool lifecyle updated with version to be ignored
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/92)
> feat: add version to lifecycle changes

- .github/workflows/terratest.yaml
Updated semantic-release-version github action to v3 to resolve CI failure
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/101)
> ci(semantic-release): Update semantic-release-version github action to v3

- test/gke_test.go
- test/wrapper.auto.tfvars
* GKE version change to fix terratest
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/109)
> fix: GKE version update to fix Terratest

- README.md
- inputs.tf
- main.tf
- modules/gcp-gke/README.md
- modules/gcp-gke/inputs.tf
- modules/gcp-gke/network.tf
* Alto needs static list of IPs from Honest to be able to allow list our traffic.
* We till now had auto NAT IP allocation.
* This change allows us to set static list of NAT IPs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/117)
> feat: add feature for manual IP addresses

- main.tf
* fix array notation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/118)
> fix: remove list notation

- modules/gcp-gke/network.tf
* remove the ignore changes lifecycle block
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/119)
> fix: remove ignore changes lifecycle

- modules/gcp-gke/modules/gcp-gke-node-pool/inputs.tf
- modules/gcp-gke/modules/gcp-gke-node-pool/node-pool.tf
- modules/gcp-gke/node-pools.tf
* Adding options to both cluster, primary node_pool as well as the additional node pools.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/134)
> feat: Add option to the node pool [DEVOP-5773]

- modules/gcp-gke/README.md
- modules/gcp-gke/inputs.tf
- modules/gcp-gke/main.tf
- test/wrapper.auto.tfvars
* Since we will disable the auto-upgrades, We want to make sure that we receive all the upgrade related notification.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/136)
> feat: Add notification for upgrades [DEVOP-5787]

- modules/example/README.md
- modules/gcp-gke/main.tf
- modules/gcp-gke/modules/gcp-gke-node-pool/node-pool.tf
* Add skip for node pool auto-upgrade checkov check
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/honestbank/terraform-gcp-gke/135)
> feat: Skip Checkov check to disable the node upgrade [DEVOP-5781]
